version: '2.1'


executors:
  docker-image:
    parameters:
      tag:
        type: string
    docker:
      - image: potyarkin/bcpp:<< parameters.tag >>


commands:
  run-tests:
    parameters:
      runner:
        type: string
        default: default
    steps:
      - run:
          name: Execute automated tests (<< parameters.runner >>)
          command: make test


jobs:
  test:
    parameters:
      runner:
        type: string
    description: test-<< parameters.runner >>
    executor:
      name: docker-image
      tag: << parameters.runner >>
    steps:
      - checkout
      - run-tests:
          runner: << parameters.runner >>


workflows:
  version: '2'
  all-tests:
    jobs:
      - test:
          name: test-debian-10
          runner: debian-10
      - test:
          name: test-debian-9
          runner: debian-9
