version: '2.1'


executors:
  docker-image:
    parameters:
      tag:
        type: string
    docker:
      - image: potyarkin/bcpp:<< parameters.tag >>


commands:
  run_tests:
    steps:
      - run:
          name: Execute automated tests
          command: make test


jobs:
  test:
    parameters:
      runner:
        type: string
    description: test-<< parameters.runner >>
    executor:
      name: docker-image
      tag: << parameters.runner >>
    steps:
      - checkout
      - run_tests


workflows:
  version: '2'
  all_tests:
    jobs:
      - test:
          runner: debian-10
      - test:
          runner: debian-9
