version: '2.1'


executors:
  docker-image:
    parameters:
      tag:
        type: string
    docker:
      - image: potyarkin/bcpp:<< parameters.tag >>
    environment:
      PIP_CACHE_DIR: ~/pip-cache
      VENVDIR: ~/venv


commands:
  run-tests:
    parameters:
      runner:
        type: string
        default: default
      cache_uid:
        type: string
        default: '1'  # increment this value to drop caches
    steps:
      - restore_cache:
          keys:
            - cache-v<< parameters.cache_uid >>-{{ arch }}-<< parameters.runner >>-{{ checksum "tests/requirements.txt" }}
            - cache-v<< parameters.cache_uid >>-{{ arch }}-<< parameters.runner >>-
      - run:
          name: Execute automated tests (<< parameters.runner >>)
          command: make test
      - save_cache:
          key: cache-v<< parameters.cache_uid >>-{{ arch }}-<< parameters.runner >>-{{ checksum "tests/requirements.txt" }}
          paths:
            - ~/pip-cache
            - ~/venv


jobs:
  test:
    parameters:
      runner:
        type: string
    description: test-<< parameters.runner >>
    executor:
      name: docker-image
      tag: << parameters.runner >>
    steps:
      - checkout
      - run-tests:
          runner: << parameters.runner >>


workflows:
  version: '2'
  all-tests:
    jobs:
      - test:
          name: test-debian-11
          runner: debian-11
      - test:
          name: test-debian-10
          runner: debian-10
      - test:
          name: test-debian-9
          runner: debian-9
      - test:
          name: test-debian-8
          runner: debian-8
      - test:
          name: test-centos-7
          runner: centos-7
      - test:
          name: test-scop-completion
          runner: scop
