# Build Docker images and push them to GitHub Container Registry

on:
  push:
    branches:
      - develop
      - dockerhub
      - master


jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: scop
      DOCKERFILE: tests/docker/${{ env.DOCKER_TAG }}.Dockerfile
      DOCKER_REPO: ghcr.io/${{ env.GITHUB_ACTOR }}/bash-complete-partial-path
      DOCKER_USER: ${{ env.GITHUB_ACTOR }}
      DOCKER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v1

      - name: Build image and push it to registry
        run: |
          echo ${{ secrets.CONTAINER_REGISTRY_PERSONAL_ACCESS_TOKEN }} \
          | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
          docker build --pull --tag $DOCKER_REPO:$DOCKER_TAG - < $DOCKERFILE
          docker push $DOCKER_REPO:$DOCKER_TAG
