name: ci/github
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'
  schedule:
    - cron: '45 3 5,15,25 * *'


jobs:
  test-linux:
    runs-on: ubuntu-latest
    name: test-${{ matrix.image }}
    container: ghcr.io/sio/bash-complete-partial-path:${{ matrix.image }}
    strategy:
      matrix:
        image:
          - bash-3.2
          - centos-7
          - debian-8
          - debian-9
          - debian-10
          - debian-11
          - scop
    env:
      PIP_CACHE_DIR: cache/pip
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: cache
          key: cache-v1-${{ runner.os }}-${{ matrix.image }}-${{ hashFiles('tests/requirements.txt') }}
      - run: make test

  test-macos:
    runs-on: macos-latest
    name: test-macos (bash-latest)
    ## TODO: Default macOS bash version (3.2) is not yet supported
    ##       Uncomment section below to enable testing with default macOS bash
    # name: test-macos (${{ matrix.bash-version }})
    # strategy:
    #   matrix:
    #     bash-version:
    #       - bash-latest
    #       - bash-default
    steps:
      - uses: actions/checkout@v1

      - name: Install GNU components
        run: brew install coreutils gnu-sed

      - name: Update GNU Bash
        run: brew install bash
        # if: matrix.bash-version == 'bash-latest'

      - name: Specify sed command
        run: echo "::set-env name=SED::gsed"
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env

      - name: Execute automated tests
        run:  make test
