name: ci/github
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'


jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OS packages for Python
        run: sudo apt install python3-venv
        if: matrix.os == 'ubuntu-latest'

      - name: Install GNU components
        run: brew install coreutils gnu-sed
        if: matrix.os == 'macos-latest'

      - name: Specify sed command
        run: echo "::set-env name=SED::gsed"
        if: matrix.os == 'macos-latest'
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env

      - name: Execute automated tests
        run:  make test
