name: ci/github
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'
  pull_request:
  schedule:
    - cron: '45 3 5,15,25 * *'


jobs:
  test-linux:
    runs-on: ubuntu-latest
    name: test-${{ matrix.image }}
    container: ghcr.io/sio/bash-complete-partial-path:${{ matrix.image }}
    strategy:
      matrix:
        image:
          - centos-7
          - debian-8
          - debian-9
          - debian-10
          - debian-11
          - debian-12
          - scop
    env:
      PIP_CACHE_DIR: cache/pip
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: cache
          key: cache-v1-${{ runner.os }}-${{ matrix.image }}-${{ hashFiles('tests/requirements.txt') }}
      - run: make test

  test-other-os:
    name: test-${{ matrix.os }}
    runs-on: ubuntu-latest
    container: potyarkin/cirrus-run
    strategy:
      matrix:
        os:
          - freebsd
          - macos
    env:
      CIRRUS_API_TOKEN: ${{ secrets.CIRRUS_API_TOKEN }}
      CIRRUS_GITHUB_REPO: ${{ secrets.CIRRUS_GITHUB_REPO }}
      CIRRUS_SHOW_BUILD_LOG: always
    steps:
      - uses: actions/checkout@v1
      - run: cirrus-run .ci/cirrus-${{ matrix.os }}.yml.j2

  test-msys2:
    runs-on: windows-latest
    env:
      PIP_CACHE_DIR: cache/pip
    defaults:
      run:
        shell: C:\msys64\usr\bin\bash.exe {0}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: cache
          key: cache-v1-${{ runner.os }}-msys2-${{ hashFiles('tests/requirements.txt') }}
      - name: make test
        run: |-
          pacman --noconfirm -Sy make python3
          make test
        env:
          PATH: '/usr/local/bin:/usr/bin:/bin'
