name: ci/github
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'


jobs:
  test-macos:
    runs-on: macos-latest
    name: test-macos (bash-latest)
    ## TODO: Default macOS bash version (3.2) is not yet supported
    ##       Uncomment section below to enable testing with default macOS bash
    # name: test-macos (${{ matrix.bash-version }})
    # strategy:
    #   matrix:
    #     bash-version:
    #       - bash-latest
    #       - bash-default
    steps:
      - uses: actions/checkout@v1

      - name: Install GNU components
        run: brew install coreutils gnu-sed

      - name: Update GNU Bash
        run: brew install bash
        # if: matrix.bash-version == 'bash-latest'

      - name: Specify sed command
        run: echo "::set-env name=SED::gsed"
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env

      - name: Execute automated tests
        run:  make test
